# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_Value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('B_Value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
