# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-20 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesScreen', '0002_auto_20180120_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='Site_Name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
